/**
 * Pixel Peeker — Resolume Advanced Output export.
 *
 * ############################################################################
 * # STATUS: UNVERIFIED AGAINST A REAL RESOLUME INSTALL.                      #
 * #                                                                          #
 * # The element names below (XmlState / versionInfo / ScreenSetup / Params / #
 * # sizing / inputs / InputSize / screens / Screen / slices / Slice) come     #
 * # from Resolume's own published documentation and forum posts. The exact    #
 * # attribute names and the Params contents have NOT been round-tripped       #
 * # through Arena, and Resolume state plainly that the screensetup XML is     #
 * # "primarily for internal use" and that they change it between releases.    #
 * #                                                                          #
 * # To fix this properly: export a screensetup preset from the target Arena   #
 * # version, diff it against `buildResolumeXml` output, and correct the       #
 * # constants in SCHEMA below. Everything version-specific is deliberately    #
 * # gathered there so the fix is one edit, not a rewrite.                     #
 * #                                                                          #
 * # Until then the UI labels this export as unverified. Do not remove that    #
 * # label without doing the round-trip test.                                  #
 * ############################################################################
 *
 * Mapping decision: one <Screen> per processor, one <Slice> per output port. That
 * makes each port's block of pixels independently positionable on the Resolume
 * composition, which is what an operator actually wants — it is the unit you move
 * when a port gets re-patched.
 */

import type { PixelMap } from '../domain/pixelmap';
import type { Project } from '../domain/types';

/** Everything that is version-specific about the file, in one place. */
const SCHEMA = {
  majorVersion: 7,
  minorVersion: 0,
  microVersion: 0,
  revision: 0,
  rootName: 'ScreenSetup',
};

function esc(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/** Resolume stores rectangles as four corner vertices, in pixels. */
function rectXml(
  tag: string,
  x: number,
  y: number,
  w: number,
  h: number,
  indent: string,
): string {
  return [
    `${indent}<${tag}>`,
    `${indent}  <Rectangle x="${x}" y="${y}" width="${w}" height="${h}"/>`,
    `${indent}</${tag}>`,
  ].join('\n');
}

export interface ResolumeOptions {
  /** Composition size. Defaults to the wall's own pixel bounding box. */
  compositionWidth?: number;
  compositionHeight?: number;
  /** One screen per processor (default) or a single screen for the whole wall. */
  screenPerProcessor?: boolean;
}

export function buildResolumeXml(
  project: Project,
  map: PixelMap,
  options: ResolumeOptions = {},
): string {
  const compW = options.compositionWidth ?? map.width;
  const compH = options.compositionHeight ?? map.height;
  const screenPerProcessor = options.screenPerProcessor ?? true;

  // Group chains into screens.
  const groups = new Map<string, typeof map.chains>();
  for (const chain of map.chains) {
    const key = screenPerProcessor ? chain.processorId : 'all';
    if (!groups.has(key)) groups.set(key, []);
    groups.get(key)!.push(chain);
  }

  const screens: string[] = [];
  for (const [key, chains] of groups) {
    const name = screenPerProcessor
      ? chains[0]?.processorName ?? key
      : project.canvas.name;

    const slices = chains
      .map((chain) => {
        const { x, y, width, height } = chain.bounds;
        return [
          `        <Slice name="${esc(`${chain.processorName} ${chain.portLabel}`)}">`,
          `          <Params/>`,
          rectXml('InputRect', x, y, width, height, '          '),
          rectXml('OutputRect', x, y, width, height, '          '),
          `        </Slice>`,
        ].join('\n');
      })
      .join('\n');

    screens.push(
      [
        `    <Screen name="${esc(name)}">`,
        `      <Params/>`,
        `      <slices>`,
        slices,
        `      </slices>`,
        `    </Screen>`,
      ].join('\n'),
    );
  }

  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    `<!-- Generated by Pixel Peeker for "${esc(project.name)}".`,
    '     UNVERIFIED FORMAT: this file has not been round-tripped through Resolume Arena.',
    '     Check it opens before relying on it, and see src/export/resolume.ts. -->',
    `<XmlState name="${SCHEMA.rootName}">`,
    `  <versionInfo majorVersion="${SCHEMA.majorVersion}" minorVersion="${SCHEMA.minorVersion}" microVersion="${SCHEMA.microVersion}" revision="${SCHEMA.revision}"/>`,
    `  <${SCHEMA.rootName}>`,
    '    <Params/>',
    '    <sizing>',
    '      <inputs>',
    `        <InputSize width="${compW}" height="${compH}"/>`,
    '      </inputs>',
    '    </sizing>',
    '    <screens>',
    ...screens,
    '    </screens>',
    `  </${SCHEMA.rootName}>`,
    '</XmlState>',
    '',
  ].join('\n');
}

/**
 * A plain slice list, in the same geometry as the XML.
 *
 * This one carries no format risk: if the XML above does not import, an operator can
 * build the same mapping by hand in a couple of minutes from this table.
 */
export function buildSliceCsv(map: PixelMap): string {
  const rows = [
    ['slice_name', 'processor', 'port', 'x', 'y', 'width', 'height', 'pixels', 'port_utilisation_pct'],
    ...map.chains.map((c) => [
      `${c.processorName} ${c.portLabel}`,
      c.processorName,
      c.portLabel,
      c.bounds.x,
      c.bounds.y,
      c.bounds.width,
      c.bounds.height,
      c.pixels,
      Math.round(c.utilisation * 100),
    ]),
  ];
  return rows.map((r) => r.join(',')).join('\n') + '\n';
}
